name: Cucumber Selenium Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   # 🔑 CLAVE para crear gh-pages

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Run tests
        run: mvn clean test
        continue-on-error: true

      - name: Generate Cucumber HTML Report
        run: |
          npm install
          node index.js
        continue-on-error: true

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/cucumber-html-report
